# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 3
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.5-node-browsers
      environment:
        PGHOST: localhost
        PGUSER: c2m2-test
        RAILS_ENV: test
    - image: circleci/postgres:12.1
      environment:
        POSTGRES_USER: c2m2-test
        POSTGRES_DB: c2m2-test_test
        POSTGRES_PASSWORD: ""

    working_directory: ~/c2m2

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - ruby-dependencies-{{ checksum "Gemfile.lock" }}

    - restore_cache:
        keys:
        - js-dependencies-{{ checksum "client/yarn.lock" }}

    - run:
        name: install javascript dependencies, build app
        command: |
          npm i

    - run:
        name: install ruby dependencies
        command: |
          bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: ruby-dependencies-{{ checksum "Gemfile.lock" }}

    - save_cache:
        paths:
        - ./client/node_modules
        key: js-dependencies-{{ checksum "client/yarn.lock" }}

    - run:
        name: wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    # Database setup
    - run:
        name: database setup
        command: |
          rake db:create
          rake db:schema:load

    # run tests!
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          rake test
