# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.4.1-node-browsers
      environment:
        PGHOST: localhost
        PGUSER: c2m2-test
        RAILS_ENV: test
    - image: circleci/postgres:10.4
      environment:
        POSTGRES_USER: c2m2-test
        POSTGRES_DB: c2m2-test_test
        POSTGRES_PASSWORD: ""

    working_directory: ~/c2m2

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-ruby-dependencies-

    - restore_cache:
        keys:
        - v1-js-dependencies-{{ checksum "client/yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-js-dependencies-

    - run:
        name: install javascript dependencies, build app
        command: |
          npm i

    - run:
        name: install ruby dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}

    - save_cache:
        paths:
        - ./client/node_modules
        key: v1-js-dependencies-{{ checksum "client/yarn.lock" }}

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    # Database setup
    - run:
        name: database setup
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    # run tests!
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          rails test
