development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: c2m2-backend_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: c2m2-backend_production
